name: Test 2-2

on:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - 'apps/app-1/README.md'
      - '!**'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test 2-2"
